application:
  domain: ${APPLICATION_DOMAIN:localhost}
efi:
  client_id: ${EFI_CLIENT_ID:}
  client_secret: ${EFI_CLIENT_SECRET:}
  url: ${EFI_URL:https://pix.api.efipay.com.br}
  base64p12: ${EFI_BASE64_P12:""}
  pixLifetime: ${EFI_PIX_LIFETIME:30}
  pixValue: ${EFI_PIX_Value:0.25}
spring:
  profiles:
    active: dev
  application:
    name: Pagamento Carnes
  web:
    resources:
      static-locations:
        - classpath:/static/
  mvc:
    favicon:
      enabled: false
jwt:
  token:
    lifetime: 3600000
    secret: your-secret-key



