efi:
  client_id: ${EFI_CLIENT_ID:}
  client_secret: ${EFI_CLIENT_SECRET:}
  url: ${EFI_URL:https://pix.api.efipay.com.br}
  base64p12: ${EFI_BASE64_P12:""}
spring:
  profiles:
    active: dev
  mustache:
    suffix: .mustache
    prefix: classpath:/templates/
  application:
    name: Pagamento Carnes
